### ISSUE TITLE
pip install containers not working

### ISSUE THREAD

**Issue by alexandrebarbaruiva** [abe-winter/containers#4]
I receive the following message when trying to install:
>Collecting containers
  Using cached https://files.pythonhosted.org/packages/29/5c/b22663c73c0d08fba9c109a56e9e34f8f2a7c6fae8d12e54837345e356d2/containers-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/1v/stknfv5905x54bjlxwj7tnfc0000gn/T/pip-install-2ktihv4b/containers/setup.py", line 11, in <module>
        REQS = load_requirements(os.path.join(os.path.dirname(__file__), 'requirements.txt'))
      File "/private/var/folders/1v/stknfv5905x54bjlxwj7tnfc0000gn/T/pip-install-2ktihv4b/containers/setup.py", line 4, in load_requirements
        lines = list(open(fname))
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/1v/stknfv5905x54bjlxwj7tnfc0000gn/T/pip-install-2ktihv4b/containers/requirements.txt'

>    ----------------------------------------
>Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/1v/stknfv5905x54bjlxwj7tnfc0000gn/T/pip-install-2ktihv4b/containers/

**Comment by abe-winter** [comment]
Thanks for the bug report. I'll take a look later today.

As a workaround, try:
```pip install git+https://github.com/abe-winter/containers.git#subdirectory=containers```

**Comment by abe-winter** [comment]
should be fixed

you may need to do `pip install --no-cache containers` to force it to re-check pypi

ping here if you're still having trouble
